
Starting Inference on file: demo/test_dataset/mouse1/anatomical/anatomical.nii
Segmentation successful for the file: 
demo/test_dataset/mouse1/anatomical/anatomical.nii

Starting Inference on file: demo/test_dataset/mouse1/dti/dti.nii
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:172: RuntimeWarning: Mean of empty slice
  masked_background_mean = np.nanmean(masked_background)
/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:174: RuntimeWarning: Mean of empty slice
  / np.nanmean(masked_background)
Slice 1 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 604, in quality_check
    roundness, elongation = geometry_check(current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 299, in geometry_check
    np.array(no_pixels) == np.amax(np.array(no_pixels)))[0][0]+1)
  File "<__array_function__ internals>", line 5, in amax
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:172: RuntimeWarning: Mean of empty slice
  masked_background_mean = np.nanmean(masked_background)
/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:174: RuntimeWarning: Mean of empty slice
  / np.nanmean(masked_background)
Slice 17 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 604, in quality_check
    roundness, elongation = geometry_check(current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 299, in geometry_check
    np.array(no_pixels) == np.amax(np.array(no_pixels)))[0][0]+1)
  File "<__array_function__ internals>", line 5, in amax
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

Segmentation successful for the file: 
demo/test_dataset/mouse1/dti/dti.nii

Starting Inference on file: demo/test_dataset/mouse1/fmri/fmri.nii
Segmentation successful for the file: 
demo/test_dataset/mouse1/fmri/fmri.nii

Starting Inference on file: demo/test_dataset/mouse1/noddi/noddi.nii
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:166: RuntimeWarning: Mean of empty slice
  masked_array_mean = np.nanmean(masked_array)
/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:167: RuntimeWarning: Mean of empty slice
  masked_array_std = np.nanstd(masked_array)/np.nanmean(masked_array)
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:172: RuntimeWarning: Mean of empty slice
  masked_background_mean = np.nanmean(masked_background)
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:174: RuntimeWarning: Mean of empty slice
  / np.nanmean(masked_background)
Slice 1 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 604, in quality_check
    roundness, elongation = geometry_check(current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 299, in geometry_check
    np.array(no_pixels) == np.amax(np.array(no_pixels)))[0][0]+1)
  File "<__array_function__ internals>", line 5, in amax
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:166: RuntimeWarning: Mean of empty slice
  masked_array_mean = np.nanmean(masked_array)
/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:167: RuntimeWarning: Mean of empty slice
  masked_array_std = np.nanstd(masked_array)/np.nanmean(masked_array)
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:172: RuntimeWarning: Mean of empty slice
  masked_background_mean = np.nanmean(masked_background)
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:174: RuntimeWarning: Mean of empty slice
  / np.nanmean(masked_background)
Slice 17 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 604, in quality_check
    roundness, elongation = geometry_check(current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 299, in geometry_check
    np.array(no_pixels) == np.amax(np.array(no_pixels)))[0][0]+1)
  File "<__array_function__ internals>", line 5, in amax
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

Segmentation successful for the file: 
demo/test_dataset/mouse1/noddi/noddi.nii

Starting Inference on file: demo/test_dataset/mouse2/anatomical/anatomical.nii
Segmentation successful for the file: 
demo/test_dataset/mouse2/anatomical/anatomical.nii

Starting Inference on file: demo/test_dataset/mouse2/dti/dti.nii
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:172: RuntimeWarning: Mean of empty slice
  masked_background_mean = np.nanmean(masked_background)
/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:174: RuntimeWarning: Mean of empty slice
  / np.nanmean(masked_background)
Slice 1 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 604, in quality_check
    roundness, elongation = geometry_check(current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 299, in geometry_check
    np.array(no_pixels) == np.amax(np.array(no_pixels)))[0][0]+1)
  File "<__array_function__ internals>", line 5, in amax
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:172: RuntimeWarning: Mean of empty slice
  masked_background_mean = np.nanmean(masked_background)
/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:174: RuntimeWarning: Mean of empty slice
  / np.nanmean(masked_background)
Slice 17 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 604, in quality_check
    roundness, elongation = geometry_check(current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 299, in geometry_check
    np.array(no_pixels) == np.amax(np.array(no_pixels)))[0][0]+1)
  File "<__array_function__ internals>", line 5, in amax
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

Segmentation successful for the file: 
demo/test_dataset/mouse2/dti/dti.nii

Starting Inference on file: demo/test_dataset/mouse2/fmri/fmri.nii
Segmentation successful for the file: 
demo/test_dataset/mouse2/fmri/fmri.nii

Starting Inference on file: demo/test_dataset/mouse2/noddi/noddi.nii
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:166: RuntimeWarning: Mean of empty slice
  masked_array_mean = np.nanmean(masked_array)
/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:167: RuntimeWarning: Mean of empty slice
  masked_array_std = np.nanstd(masked_array)/np.nanmean(masked_array)
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:172: RuntimeWarning: Mean of empty slice
  masked_background_mean = np.nanmean(masked_background)
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:174: RuntimeWarning: Mean of empty slice
  / np.nanmean(masked_background)
Slice 1 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 604, in quality_check
    roundness, elongation = geometry_check(current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 299, in geometry_check
    np.array(no_pixels) == np.amax(np.array(no_pixels)))[0][0]+1)
  File "<__array_function__ internals>", line 5, in amax
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:166: RuntimeWarning: Mean of empty slice
  masked_array_mean = np.nanmean(masked_array)
/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:167: RuntimeWarning: Mean of empty slice
  masked_array_std = np.nanstd(masked_array)/np.nanmean(masked_array)
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:172: RuntimeWarning: Mean of empty slice
  masked_background_mean = np.nanmean(masked_background)
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:174: RuntimeWarning: Mean of empty slice
  / np.nanmean(masked_background)
Slice 17 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 604, in quality_check
    roundness, elongation = geometry_check(current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 299, in geometry_check
    np.array(no_pixels) == np.amax(np.array(no_pixels)))[0][0]+1)
  File "<__array_function__ internals>", line 5, in amax
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

Segmentation successful for the file: 
demo/test_dataset/mouse2/noddi/noddi.nii

Starting Inference on file: demo/test_dataset/mouse3/anatomical/20180618_100038_Mouse_Jackson1_1_1_niftianatomical_data.nii.gz
Segmentation successful for the file: 
demo/test_dataset/mouse3/anatomical/20180618_100038_Mouse_Jackson1_1_1_niftianatomical_data.nii.gz

Starting Inference on file: demo/test_dataset/mouse3/dti/20180618_100038_Mouse_Jackson1_1_1_niftidti_data.nii.gz
Segmentation successful for the file: 
demo/test_dataset/mouse3/dti/20180618_100038_Mouse_Jackson1_1_1_niftidti_data.nii.gz

Starting Inference on file: demo/test_dataset/mouse3/fmri/20180618_100038_Mouse_Jackson1_1_1_niftifmri_data.nii.gz
Segmentation successful for the file: 
demo/test_dataset/mouse3/fmri/20180618_100038_Mouse_Jackson1_1_1_niftifmri_data.nii.gz

Starting Inference on file: demo/test_dataset/mouse4_4d/dti/data.nii.gz
Slice 1 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 604, in quality_check
    roundness, elongation = geometry_check(current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 299, in geometry_check
    np.array(no_pixels) == np.amax(np.array(no_pixels)))[0][0]+1)
  File "<__array_function__ internals>", line 5, in amax
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:166: RuntimeWarning: Mean of empty slice
  masked_array_mean = np.nanmean(masked_array)
/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:167: RuntimeWarning: Mean of empty slice
  masked_array_std = np.nanstd(masked_array)/np.nanmean(masked_array)
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:172: RuntimeWarning: Mean of empty slice
  masked_background_mean = np.nanmean(masked_background)
/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py:174: RuntimeWarning: Mean of empty slice
  / np.nanmean(masked_background)
Slice 17 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 604, in quality_check
    roundness, elongation = geometry_check(current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 299, in geometry_check
    np.array(no_pixels) == np.amax(np.array(no_pixels)))[0][0]+1)
  File "<__array_function__ internals>", line 5, in amax
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/frohoz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

Segmentation successful for the file: 
demo/test_dataset/mouse4_4d/dti/data.nii.gz

Starting Inference on file: demo/test_dataset/mouse5_extrafiles/anatomical/anatomical.nii
Segmentation successful for the file: 
demo/test_dataset/mouse5_extrafiles/anatomical/anatomical.nii
Segmentation has failed for the file: 
demo/test_dataset/mouse5_extrafiles/anatomical/anatomical.nii
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/workflows.py", line 85, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Zero files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse6_uf_dti_original/dti Ensure that there is exactly 1 image file in each subdirectory

