
Starting Inference on file: demo/test_dataset/mouse1/anatomical/anatomical.nii
Segmentation has failed for the file: 
demo/test_dataset/mouse1/anatomical/anatomical.nii
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/msUNET/predict/core/workflows.py", line 94, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Multiple files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse1/anatomical Ensure that there is only 1 image file in each subdirectory


Starting Inference on file: demo/test_dataset/mouse1/dti/dti_mask_likelihood.nii
Segmentation has failed for the file: 
demo/test_dataset/mouse1/dti/dti_mask_likelihood.nii
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/msUNET/predict/core/workflows.py", line 94, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Multiple files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse1/dti Ensure that there is only 1 image file in each subdirectory


Starting Inference on file: demo/test_dataset/mouse1/fmri/fmri.nii
Segmentation has failed for the file: 
demo/test_dataset/mouse1/fmri/fmri.nii
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/msUNET/predict/core/workflows.py", line 94, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Multiple files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse1/fmri Ensure that there is only 1 image file in each subdirectory


Starting Inference on file: demo/test_dataset/mouse1/noddi/noddi_mask_likelihood.nii
Segmentation has failed for the file: 
demo/test_dataset/mouse1/noddi/noddi_mask_likelihood.nii
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/msUNET/predict/core/workflows.py", line 94, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Multiple files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse1/noddi Ensure that there is only 1 image file in each subdirectory


Starting Inference on file: demo/test_dataset/mouse2/anatomical/anatomical.nii
Segmentation has failed for the file: 
demo/test_dataset/mouse2/anatomical/anatomical.nii
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/msUNET/predict/core/workflows.py", line 94, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Multiple files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse2/anatomical Ensure that there is only 1 image file in each subdirectory


Starting Inference on file: demo/test_dataset/mouse2/dti/dti_mask_likelihood.nii
Segmentation has failed for the file: 
demo/test_dataset/mouse2/dti/dti_mask_likelihood.nii
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/msUNET/predict/core/workflows.py", line 94, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Multiple files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse2/dti Ensure that there is only 1 image file in each subdirectory


Starting Inference on file: demo/test_dataset/mouse2/fmri/fmri.nii
Segmentation has failed for the file: 
demo/test_dataset/mouse2/fmri/fmri.nii
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/msUNET/predict/core/workflows.py", line 94, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Multiple files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse2/fmri Ensure that there is only 1 image file in each subdirectory


Starting Inference on file: demo/test_dataset/mouse2/noddi/noddi_mask_likelihood.nii
Segmentation has failed for the file: 
demo/test_dataset/mouse2/noddi/noddi_mask_likelihood.nii
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/msUNET/predict/core/workflows.py", line 94, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Multiple files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse2/noddi Ensure that there is only 1 image file in each subdirectory


Starting Inference on file: demo/test_dataset/mouse3/anatomical/20180618_100038_Mouse_Jackson1_1_1_niftianatomical_data_mask.nii.gz
Segmentation has failed for the file: 
demo/test_dataset/mouse3/anatomical/20180618_100038_Mouse_Jackson1_1_1_niftianatomical_data_mask.nii.gz
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/msUNET/predict/core/workflows.py", line 94, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Multiple files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse3/anatomical Ensure that there is only 1 image file in each subdirectory


Starting Inference on file: demo/test_dataset/mouse3/dti/20180618_100038_Mouse_Jackson1_1_1_niftidti_data.nii.gz
Segmentation has failed for the file: 
demo/test_dataset/mouse3/dti/20180618_100038_Mouse_Jackson1_1_1_niftidti_data.nii.gz
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/msUNET/predict/core/workflows.py", line 94, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Multiple files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse3/dti Ensure that there is only 1 image file in each subdirectory


Starting Inference on file: demo/test_dataset/mouse3/fmri/20180618_100038_Mouse_Jackson1_1_1_niftifmri_data_mask_likelihood.nii
Segmentation has failed for the file: 
demo/test_dataset/mouse3/fmri/20180618_100038_Mouse_Jackson1_1_1_niftifmri_data_mask_likelihood.nii
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/msUNET/predict/core/workflows.py", line 94, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Multiple files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse3/fmri Ensure that there is only 1 image file in each subdirectory

Segmentation has failed for the file: 
demo/test_dataset/mouse3/fmri/20180618_100038_Mouse_Jackson1_1_1_niftifmri_data_mask_likelihood.nii
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/msUNET/predict/core/workflows.py", line 83, in segment_file_structure_workflow
    raise RuntimeError(
RuntimeError: Zero files with extension .nii or .nii.gz found in the dataset subdirectory demo/test_dataset/mouse5_4d/anatomical Ensure that there is exactly 1 image file in each subdirectory

