Slice 1 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 2 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 3 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 4 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 5 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 6 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 7 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 8 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 9 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 10 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 11 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 12 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 13 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 14 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 15 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 16 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 17 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 18 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 19 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 20 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 21 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 22 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 23 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 24 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 25 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 26 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 27 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 28 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 29 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 30 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 31 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 32 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 33 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 34 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 35 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 36 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 37 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 38 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 39 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 40 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 41 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 42 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 43 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 44 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 45 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 46 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 47 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 48 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 49 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 50 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 51 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 52 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 53 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 54 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 55 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 56 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 57 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 58 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 59 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Slice 60 experienced an error while calculating QC features. This is non-fatal, but notable if frequently observed
The error is as follows:
Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 595, in quality_check
    = edge_detection(current_data_slice, current_mask_slice)
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 236, in edge_detection
    chamfer_dist = chamfer_distance(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 438, in chamfer_distance
    av_dist1 = array2samples_distance(array1[i], array2[i])
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 412, in array2samples_distance
    distances = np.linalg.norm(expanded_array1-expanded_array2, axis=1)
ValueError: operands could not be broadcast together with shapes (4225,70) (3900,70) 

Segmentation has failed for the file: 
demo/test_dataset/mouse6_uf_dti_original/dti/dti.nii.gz
With the below error: 

Traceback (most recent call last):
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/workflows.py", line 223, in segment_file_structure_workflow
    quality_check_temp = segment_image_workflow(
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/workflows.py", line 542, in segment_image_workflow
    file_quality_check_df = quality_check(inference_array,
  File "/Users/frohoz/Documents/GitHub/seg-for-4modalities/seg-for-4modalities/predict/core/quality.py", line 588, in quality_check
    current_mask_slice = mask_array[i, :, :]
IndexError: index 60 is out of bounds for axis 0 with size 60

